src/Entity/Pack.php
<?php

namespace App\Entity;
use App\Entity\Typepack;
use App\Repository\PackRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PackRepository::class)]
class Pack
{
    #[ORM\Id] // Annotation pour indiquer que cette propriété est une clé primaire
    #[ORM\GeneratedValue] // Annotation pour indiquer que la valeur de cette propriété est générée automatiquement
    #[ORM\Column] // Annotation pour indiquer que cette propriété est mappée à une colonne de la table
    private ?int $id_pack = null; // Déclaration de la propriété avec un type nullable (int)

    #[ORM\Column(length: 255)] // Annotation pour indiquer les détails de la colonne dans la base de données
    private ?string $nom_pack = null; // Déclaration de la propriété avec un type nullable (string)

    #[ORM\Column(length: 255)] // Annotation pour indiquer les détails de la colonne dans la base de données
    private ?string $Description_pack = null; // Déclaration de la propriété avec un type nullable (string)

    #[ORM\Column] // Annotation pour indiquer les détails de la colonne dans la base de données
    private ?float $Prix = null; // Déclaration de la propriété avec un type nullable (float)

    #[ORM\Column(type: Types::DATE_MUTABLE)] // Annotation pour indiquer les détails de la colonne dans la base de données
    private ?\DateTimeInterface $Date = null; // Déclaration de la propriété avec un type nullable (\DateTimeInterface)

    #[ORM\Column(length: 255)] // Annotation pour indiquer les détails de la colonne dans la base de données
    private ?string $Image = null; // Déclaration de la propriété avec un type nullable (string)

    #[ORM\ManyToOne(targetEntity: Typepack::class)] // Annotation pour indiquer la relation ManyToOne avec l'entité Typepack
    #[ORM\JoinColumn(name: "id_typepack", referencedColumnName: "id_typepack", nullable: false)] // Annotation pour configurer la jointure
    private ?Typepack $Type_pack = null; // Déclaration de la propriété avec un type nullable (Typepack)

    // Les autres méthodes de l'entité Pack...

    // Méthodes getters et setters pour accéder et définir les valeurs des propriétés

    public function getId_pack(): ?int
    {
        return $this->id_pack;
    }

    public function getNomPack(): ?string
    {
        return $this->nom_pack;
    }

    public function setNomPack(string $nom_pack): static
    {
        $this->nom_pack = $nom_pack;

        return $this;
    }

    public function getDescriptionPack(): ?string
    {
        return $this->Description_pack;
    }

    public function setDescriptionPack(string $Description_pack): static
    {
        $this->Description_pack = $Description_pack;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): static
    {
        $this->Date = $Date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getTypePack(): ?string
    {
        return $this->Type_pack ? $this->Type_pack->getNomTypePack() : null;
    }

    public function setTypePack(?Typepack $Type_pack): static
    {
        $this->Type_pack = $Type_pack;

        return $this;
    }
}

src/Form/PackType.php
<?php

namespace App\Form;

use App\Entity\Pack; // Utilisation de l'entité Pack
use App\Entity\Typepack;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\File;
class PackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom_pack', TextType::class, [ // Modification du nom du champ pour correspondre à l'attribut de l'entité Pack
                'label' => 'Nom du pack', // Modifier le label si nécessaire
                'constraints' => [
                    new NotBlank(),
                    new Length(['max' => 255]),
                ]
            ])
            ->add('Type_pack', ChoiceType::class, [
                'label' => 'Type de pack',
                'choices' => $options['types'],
                'choice_label' => function (Typepack $typepack) {
                    return $typepack->getNomTypePack();
                },
                'constraints' => [
                    new NotBlank(),
                ]
            ])
            ->add('Description_pack', TextareaType::class, [
                'label' => 'Description du pack',
                'constraints' => [
                    new NotBlank(),
                ]
            ])
            ->add('Prix', MoneyType::class, [
                'label' => 'Prix',
                'constraints' => [
                    new NotBlank(),
                    new GreaterThanOrEqual(0),
                ]
            ])
            ->add('Date', DateType::class, [
                'label' => 'Date',
                'widget' => 'single_text',
                'html5' => true,
                'data' => new \DateTime(),
                'constraints' => [
                    new NotBlank(),
                    // Ajoutez d'autres contraintes de validation au besoin
                ],
            ])
            ->add('Image', FileType::class, [
                'label' => 'Image (JPEG/PNG files)',
                'required' => false, // le champ n'est pas requis
                'mapped' => false, // ne pas mapper ce champ à l'entité
                'multiple' => false, // autoriser uniquement un fichier à être téléchargé
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un fichier JPEG ou PNG valide',
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pack::class, // Utilisation de l'entité Pack
            'types' => [], // Définit une option 'types' par défaut comme un tableau vide
        ]);
    }
}

src/Controller/PackController.php
<?php

namespace App\Controller;

use App\Entity\Pack;
use App\Form\PackType;
use App\Repository\PackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use App\Entity\Typepack; // Importez l'entité Typepack

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
#[Route('/pack')]
class PackController extends AbstractController
{
    #[Route('/', name: 'app_pack_index', methods: ['GET'])]
    public function index(PackRepository $packRepository): Response
    {
        return $this->render('pack/index.html.twig', [
            'packs' => $packRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ParameterBagInterface $parameterBag): Response
    {
        // Récupérer tous les types de pack disponibles depuis la base de données
        $typesDePack = $this->getDoctrine()->getRepository(Typepack::class)->findAll();
    
        // Créer le formulaire
        $pack = new Pack();
        // Créez le formulaire en passant l'instance de Pack
        $form = $this->createForm(PackType::class, $pack, ['types' => $typesDePack]);
    
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer le type de pack sélectionné
            $typePackSelectionne = $form->get('Type_pack')->getData();
    
            // Utiliser le type de pack pour mettre à jour le pack personnalisé
            $this->updatePackWithTypePack($pack, $typePackSelectionne);
    
            // Obtenez le répertoire d'images à partir du conteneur de paramètres
            $imagesDirectory = $parameterBag->get('kernel.project_dir') . '/public/uploads/images';
    
            // Traitement de l'image téléchargée
            $imageFile = $form->get('Image')->getData();
    
            if ($imageFile) {
                $imageName = uniqid().'.'.$imageFile->guessExtension();
                $imageFile->move($imagesDirectory, $imageName);
    
                // Assignation de l'emplacement de l'image à l'entité
                $pack->setImage($imageName);
            }
    
            // Persist et flush de l'entité dans la base de données
            $entityManager->persist($pack);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_pack_index');
        }
    
        return $this->renderForm('pack/new.html.twig', [
            'pack' => $pack, // Correction ici, 'pack' au lieu de 'packs'
            'form' => $form,
        ]);
    }
    private function updatePackWithTypePack(PacK $pack, Typepack $typepack)
    {
        // Mettre à jour les propriétés du pack personnalisé en fonction du type de pack sélectionné
        $pack->setTypePack($typepack);
    
        // Autres mises à jour du pack personnalisé si nécessaire
    }


    #[Route('/{id}', name: 'app_pack_show', methods: ['GET'])]
    public function show(Pack $pack): Response
    {
        return $this->render('pack/show.html.twig', [
            'pack' => $pack,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pack_edit', methods: ['GET', 'POST'])]
public function edit(Request $request, Pack $pack): Response
{
    // Récupérer tous les types de pack depuis la base de données
    $typesDePack = $this->getDoctrine()->getRepository(Typepack::class)->findAll();

    // Créer le formulaire et passer les types de pack en option
    $form = $this->createForm(PackType::class, $pack, [
        'types' => $typesDePack,
    ]);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Récupérer le fichier d'image soumis
        $imageFile = $form->get('Image')->getData();

        if ($imageFile) {
            // Déplacer le fichier téléchargé vers le répertoire souhaité
            $destination = $this->getParameter('kernel.project_dir').'/public/uploads/images';
            $newFilename = uniqid().'.'.$imageFile->guessExtension();

            try {
                $imageFile->move($destination, $newFilename);
                $pack->setImage($newFilename); // Définir le nom du fichier dans l'entité
            } catch (FileException $e) {
                // Gérer l'exception si le déplacement du fichier a échoué
            }
        }

        // Enregistrer les modifications dans la base de données
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
    }

    // Rendre le formulaire dans le template
    return $this->render('pack/edit.html.twig', [
        'pack' => $pack,
        'form' => $form->createView(),
    ]);
}


    #[Route('/{id}', name: 'app_pack_delete', methods: ['POST'])]
    public function delete(Request $request, Pack $pack, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pack->getId_pack(), $request->request->get('_token'))) {
            $entityManager->remove($pack);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pack/_delete_form.html.twig
<form method="post" action="{{ path('app_pack_delete', {'id': pack.id_pack}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pack.id_pack) }}">
    <button class="btn">Delete</button>
</form>

templates/pack/_form.html.twig
{% extends '/back/base.html.twig' %}

{% block body %}
    <style>
        .custom-form-background {
            background-color: #f8f9fa; /* Couleur d'arrière-plan */
            padding: 20px; /* Marge intérieure pour l'espace autour du formulaire */
            border-radius: 10px; /* Arrondi les coins du formulaire */
        }
        .error-message {
            color: #721c24; /* Couleur du texte pour les messages d'erreur */
            background-color: #f8d7da; /* Couleur de fond pour les messages d'erreur */
            padding: 10px; /* Marge intérieure pour l'espace autour du message d'erreur */
            border-radius: 5px; /* Arrondi les coins du message d'erreur */
            margin-top: 5px; /* Marge supérieure pour l'espace entre le message d'erreur et le champ de saisie */
        }
    </style>

    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card custom-form-background">
                    <div class="card-body">
                        <h5 class="card-title mb-4 text-center">Create New Pack</h5>
                        {{ form_start(form, {'attr': {'class': 'row g-3'}}) }}
                            <div class="col-md-12">
                               {{ form_row(form.Nom_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Type_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Description_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Prix, {'attr': {'class': 'form-control'}}) }}
                                {% if form.vars.errors['Prix'] is defined and form.vars.errors['Prix']|length > 0 %}
                                    <div class="error-message">Le prix ne peut pas être négatif.</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Date, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Image, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pack/edit.html.twig
{% extends 'back/base.html.twig' %}

{% block body %}
    <style>
        .custom-form-background {
            background-color: #f8f9fa; /* Couleur d'arrière-plan */
            padding: 20px; /* Marge intérieure pour l'espace autour du formulaire */
            border-radius: 10px; /* Arrondi les coins du formulaire */
        }
        .error-message {
            color: #721c24; /* Couleur du texte pour les messages d'erreur */
            background-color: #f8d7da; /* Couleur de fond pour les messages d'erreur */
            padding: 10px; /* Marge intérieure pour l'espace autour du message d'erreur */
            border-radius: 5px; /* Arrondi les coins du message d'erreur */
            margin-top: 5px; /* Marge supérieure pour l'espace entre le message d'erreur et le champ de saisie */
        }
    </style>

    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card custom-form-background">
                    <div class="card-body">
                        <h5 class="card-title mb-4 text-center">Edit Pack</h5>
                        {{ form_start(form, {'attr': {'class': 'row g-3'}}) }}
                            <div class="col-md-12">
                                {{ form_row(form.Nom_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Type_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Description_pack, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Prix, {'attr': {'class': 'form-control'}}) }}
                                {% if form.vars.errors['Prix'] is defined and form.vars.errors['Prix']|length > 0 %}
                                    <div class="error-message">Le prix ne peut pas être négatif.</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Date, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-md-12">
                                {{ form_row(form.Image, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pack/index.html.twig
{% extends '/back/base.html.twig' %}

{% block title %}Pack{% endblock %}

{% block body %}
    <div class="container-fluid" style="margin-top: 40px; overflow-x: auto;">
        <div class="row">
            <div class="col-md-3" style="padding-right: 20px;">
                {# Ajoutez votre barre latérale ici #}
            </div>
            <div class="col-md-9">
                <div class="table-container">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nom Pack</th>
                                <th>Type Pack</th>
                                <th>Description Pack</th>
                                <th>Prix</th>
                                <th>Date</th>
                                <th>Image</th>
                                <th>show</th>
                                <th>edit</th>
                                <th>delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pack in packs %}
                                <tr>
                                    <td>{{ pack.id_pack }}</td>
                                    <td>{{ pack.getNomPack() }}</td>
                                    <td>{{ pack.getTypePack() }}</td> {# Utilisez la méthode getTypePack() pour obtenir le nom du type de pack #}
                                    <td>{{ pack.Descriptionpack }}</td>
                                    <td>{{ pack.Prix }}</td>
                                    <td>{{ pack.Date ? pack.Date|date('Y-m-d') : '' }}</td>
                                    <td><img src="{{ asset('uploads/images/' ~ pack.Image) }}" alt="Image" width="200"></td>
                                    <td>
                                        <a href="{{ path('app_pack_show', {'id': pack.id_pack}) }}" class="btn btn-primary">Show</a>
                                    </td>
                                    <td>
                                        <a href="{{ path('app_pack_edit', {'id': pack.id_pack}) }}" class="btn btn-secondary">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{ path('app_pack_delete', {'id': pack.id_pack}) }}" method="post">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pack.id_pack) }}">
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="10">No records found</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <a href="{{ path('app_pack_new') }}" class="btn btn-success">Create new</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/pack/new.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Create new Pack{% endblock %}

{% block body %}
    <h1>Create new Pack</h1>

    {% for message in app.flashes('error') %}
    <div class="alert alert-danger text-center mb-4" role="alert">
        <strong>{{ message }}</strong>
    </div>
{% endfor %}

    {{ include('pack/_form.html.twig') }}

    <a href="{{ path('app_pack_index') }}">Back to list</a>
{% endblock %}

templates/pack/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Détails du Pack{% endblock %}

{% block body %}
<div class="container">
    <header>
        <h1 class="text-center mt-5 mb-4">Détails du Pack</h1>
    </header>

    <section class="details-section">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <article class="card bg-light mb-4">
                    <header class="card-header bg-primary text-white">
                        <h2 class="text-center">{{ pack.nomPack }}</h2>
                    </header>
                    <div class="card-body text-center">
                        <img src="{{ asset('uploads/images/' ~ pack.Image) }}" alt="Image" class="img-fluid rounded mb-4 border border-primary mx-auto d-block" width="300">
                        <div class="pack-details">
                            <p class="pack-description">{{ pack.DescriptionPack }}</p>
                            <p><strong>Type de Pack:</strong> {{ pack.TypePack }}</p>
                            <p><strong>Prix:</strong> {{ pack.Prix }}</p>
                        </div>
                    </div>
                    <footer class="card-footer bg-light">
                        <p class="pack-date text-muted">{{ pack.Date ? pack.Date|date('Y-m-d') : '' }}</p>
                        <div class="text-center mt-3">
                            <a href="{{ path('app_pack_index') }}" class="btn btn-outline-primary mr-2">Retour à la liste</a>
                            <a href="{{ path('app_pack_edit', {'id': pack.id_pack}) }}" class="btn btn-primary mr-2">Modifier</a>
                            {{ include('pack/_delete_form.html.twig') }}
                        </div>
                    </footer>
                </article>
            </div>
        </div>
    </section>
</div>
{% endblock %}